Update LRU to 0.6.5
This fixes the following crash:

	thread 'main' panicked at 'attempted to leave type `lru::LruEntry<u32, dex::string::DexString>` uninitialized, which is invalid', /home/keegan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:660:9
	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace